import type { PageContent } from '../types'

const c = {
  brief: (s: string) => s,
}

export const overview: PageContent = {
  id: 'overview',
  title: 'Harness 全景',
  emoji: '🏠',
  subtitle: 'DeepSeek Harness 到底由什么组成 —— 一切皆插件',
  hero: [
    'DeepSeek Harness（dsh）是一个「everything is a plugin」的 Agent 运行时。它不是一个大而全的程序，而是一个 Cordis 宿主 + 一组功能插件：核心执行、工具、技能、子代理、工作流、会话、沙箱、Web UI……全部以插件的形式组合。',
    '一个「Profile」决定把哪些插件组装成一个可运行的实例（如 web、headless），最终通过 dsh CLI 启动。下图是顶层结构 —— 每一条边都代表真实源码中的注册或调用关系，点击节点可直达源码。',
  ],
  learn: [
    'Harness 的顶层组成',
    '核心包族 core 提供什么',
    '能力 Seam（Definition/Provider/Consumer）',
    'Profile 与 Bundle 如何组合',
    'Agent Loop 在整图中的位置',
  ],
  nodes: [
    { id: 'user', label: '用户', kind: 'user', brief: '通过 CLI 或 Web 界面发起提问', icon: '🧑' },
    {
      id: 'cli', label: 'dsh CLI', kind: 'file',
      brief: 'apps/cli —— 命令行入口，dsh --profile web 启动 web 实例',
      detail: '官方 CLI 入口，负责解析 profile、加载 bundle、启动 Cordis 宿主并监听。',
      sources: [{ path: 'apps/cli', label: 'apps/cli' }],
    },
    {
      id: 'web', label: 'Web Client', kind: 'bundle',
      brief: 'React 客户端 + UI 插件（Slots 系统）',
      detail: '浏览器端由 packages/client/* 的 39 个插件组成，通过 ctx.slots.register 把 UI 挂到 slot 树上。',
      sources: [{ path: 'packages/client/web', label: 'client/web' }],
      docs: [{ path: 'packages/client/AGENTS.md', label: 'client/AGENTS.md' }],
    },
    {
      id: 'profile', label: 'Profile', kind: 'profile',
      brief: 'dsh --profile web 决定加载哪些 bundle/插件',
      detail: 'Profile 是「要启动哪些插件」的声明。bundle 是插件组合包：dsh-base 打底，dsh-web-app 叠加 Web UI。',
      sources: [{ path: 'packages/bundle/base', label: 'bundle/base' }, { path: 'packages/bundle/web-app', label: 'bundle/web-app' }],
      docs: [{ path: 'docs/development.md', label: 'development.md' }],
    },
    {
      id: 'core', label: 'core 核心包族', kind: 'package',
      brief: 'agent / agent-loop / tools / session / system-prompt / scope',
      detail: '一切执行的心脏：AgentRegistry(ctx.agents)、AgentLoop(ctx.agentLoop)、ToolRuntime(ctx.tools)、SessionStore(ctx.sessions)、SystemPrompt(ctx.systemPrompt)、ScopedLayers(ctx.scope)。',
      sources: [{ path: 'packages/core/agent/src/index.ts', label: 'core/agent' }, { path: 'packages/core/agent-loop/src/agent.ts', label: 'core/agent-loop' }, { path: 'packages/core/tools/src/index.ts', label: 'core/tools' }, { path: 'packages/core/session/src/index.ts', label: 'core/session' }],
    },
    {
      id: 'loop', label: 'Agent Loop', kind: 'concept',
      brief: 'ReactLoopAgent：turn → step → LLM → tool → result',
      detail: '一轮执行由 packages/core/agent-loop/src/agent.ts 的 ReactLoopAgent 驱动；工具并行调度在 tool-calls.ts。每次动作都写入 Session 事件日志。',
      sources: [{ path: 'packages/core/agent-loop/src/agent.ts', label: 'agent.ts' }, { path: 'packages/core/agent-loop/src/tool-calls.ts', label: 'tool-calls.ts' }],
      docs: [{ path: 'docs/agent-lifecycle.md', label: 'agent-lifecycle.md' }],
    },
    {
      id: 'llm', label: 'ctx.llm', kind: 'ctx',
      brief: 'LlmRuntime：LLM 抽象层，适配 DeepSeek/Pi.AI 等',
      detail: 'packages/llm/llm 提供 LlmRuntime，通过 registerAdapter 注册 provider adapter；llm/stream 是路由级 waterfall 扩展点。',
      sources: [{ path: 'packages/llm/llm/src/index.ts', label: 'llm/llm' }],
    },
    {
      id: 'tools', label: 'ctx.tools', kind: 'ctx',
      brief: 'ToolRuntime：工具注册 + pre/execute/post 管线',
      detail: 'packages/core/tools 的工具运行时，负责 schema、预执行策略（allow/deny/ask）、执行、后处理、结果物化。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'core/tools' }],
    },
    {
      id: 'session', label: 'ctx.sessions', kind: 'ctx',
      brief: 'SessionStore：append-only 事件日志，单一事实源',
      detail: 'packages/core/session。所有 turn/step/tool/assistant 事件追加进日志；LLM 历史从日志派生；持久化走 session-persistence。',
      sources: [{ path: 'packages/core/session/src/index.ts', label: 'core/session' }],
    },
    {
      id: 'skills', label: 'ctx.skills', kind: 'ctx',
      brief: 'SkillRegistry：技能注册表（Provider → Catalog → Loader）',
      detail: 'packages/skill/*。skill-filesystem 提供本地技能，tool-skill 把技能目录注入模型。',
      sources: [{ path: 'packages/skill/skill/src/index.ts', label: 'skill/skill' }],
      docs: [{ path: 'docs/subsystems/skills.md', label: 'skills.md' }],
    },
    {
      id: 'subagent', label: 'ctx.subagents', kind: 'ctx',
      brief: 'SubagentRuntime：创建/控制子 Agent',
      detail: 'packages/subagent/*。spawn=fresh child、fork=继承上下文，还有 ACP/Codex/Claude Code 等远程后端。',
      sources: [{ path: 'packages/subagent/subagent/src/index.ts', label: 'subagent/subagent' }],
      docs: [{ path: 'docs/subsystems/subagent.md', label: 'subagent.md' }],
    },
    {
      id: 'workflow', label: 'ctx.workflowEngine', kind: 'ctx',
      brief: 'WorkflowEngine：脚本化编排多个 Subagent',
      detail: 'packages/workflow/*。worker-thread 引擎在隔离线程跑 workflow 脚本，脚本内可 agent()/parallel()/pipeline()。',
      sources: [{ path: 'packages/workflow/workflow/src/index.ts', label: 'workflow/workflow' }],
      docs: [{ path: 'docs/subsystems/workflow.md', label: 'workflow.md' }],
    },
    {
      id: 'sandbox', label: 'ctx.sandbox', kind: 'ctx',
      brief: 'SandboxProvider：子进程文件效应沙箱',
      detail: 'packages/sandbox/*。Linux bwrap/Landlock、macOS Seatbelt、Windows ACL；fail closed 不静默退化。',
      sources: [{ path: 'packages/sandbox/sandbox/src/index.ts', label: 'sandbox/sandbox' }],
      docs: [{ path: 'docs/subsystems/sandbox.md', label: 'sandbox.md' }],
    },
  ],
  edges: [
    { id: 'e-user-cli', from: 'user', to: 'cli', label: '发起提问' },
    { id: 'e-user-web', from: 'user', to: 'web', label: 'Web 界面' },
    { id: 'e-cli-profile', from: 'cli', to: 'profile', label: '--profile web' },
    { id: 'e-web-profile', from: 'web', to: 'profile', label: 'client shell' },
    { id: 'e-profile-core', from: 'profile', to: 'core', label: '组装' },
    { id: 'e-core-loop', from: 'core', to: 'loop', label: '驱动' },
    { id: 'e-loop-llm', from: 'loop', to: 'llm', label: 'agent/request → llm/stream' },
    { id: 'e-loop-tools', from: 'loop', to: 'tools', label: 'tool/call' },
    { id: 'e-loop-session', from: 'loop', to: 'session', label: 'append 事件' },
    { id: 'e-loop-skills', from: 'loop', to: 'skills', label: '注入目录' },
    { id: 'e-loop-subagent', from: 'loop', to: 'subagent', label: 'delegation' },
    { id: 'e-loop-workflow', from: 'loop', to: 'workflow', label: 'workflow 工具' },
    { id: 'e-tools-sandbox', from: 'tools', to: 'sandbox', label: 'bash/fs 沙箱' },
    { id: 'e-web-session', from: 'web', to: 'session', label: '渲染事件流' },
  ],
  concepts: [
    {
      title: 'Everything is a plugin',
      icon: '🧩',
      body: '连核心执行、会话、工具都不是内建的，而是以插件形式挂到 Cordis 宿主上。加一个能力 = 加一个插件；改行为 = 在 ctx 上监听/拦截事件。',
      sources: [{ path: 'docs/architecture.md', label: 'architecture.md' }],
    },
    {
      title: '能力 Seam：Definition / Provider / Consumer',
      icon: '🔌',
      body: '一个能力缝由三部分组成：Service Definition 定义 ctx 键与接口；Provider 提供具体实现（可多个按名共存）；Consumer 消费它。例如 Skills：skill 定义 ctx.skills，skill-filesystem 是 Provider，tool-skill 是 Consumer。',
      sources: [{ path: 'docs/subsystems/skills.md', label: 'skills.md' }],
    },
    {
      title: 'Profile + Bundle = 可运行实例',
      icon: '🧬',
      body: 'bundle 是「插件组合包」（dsh-base 打底、dsh-web-app 叠加 UI）。profile 选择加载哪些 bundle/插件。dsh --profile web --dump-config 可打印当前机器实际启动的插件树。',
      sources: [{ path: 'packages/bundle/base', label: 'bundle/base' }],
    },
    {
      title: 'Session 是单一事实源',
      icon: '💾',
      body: '一次交互的完整历史（模型消息、工具调用、流式 chunk、审批）都追加进 append-only 的 SessionEvent 日志；模型看到的 LLM 历史是从日志「派生」出来的投影，而不是单独存储。',
      sources: [{ path: 'packages/core/session/src/types.ts', label: 'session/types.ts' }],
    },
    {
      title: 'durable 与 live 两层事件',
      icon: '⚡',
      body: 'turn/*、step/*、tool/* 等 durable 事件决定「发生了什么」（进日志可回放）；agent/*、tools/* 等 live 事件决定「下一步怎么做」（瀑布式扩展点，可拦截）。',
      sources: [{ path: 'docs/agent-lifecycle.md', label: 'agent-lifecycle.md' }],
    },
  ],
  packages: [
    'packages/core/agent',
    'packages/core/agent-loop',
    'packages/core/tools',
    'packages/core/session',
    'packages/bundle/base',
    'packages/llm/llm',
    'packages/skill/skill',
    'packages/subagent/subagent',
    'packages/workflow/workflow',
    'packages/sandbox/sandbox',
    'packages/client/web',
  ],
  docs: [
    { path: 'docs/architecture.md', label: 'docs/architecture.md' },
    { path: 'docs/agent-lifecycle.md', label: 'docs/agent-lifecycle.md' },
    { path: 'docs/subsystems/core.md', label: 'docs/subsystems/core.md' },
    { path: 'packages/README.md', label: 'packages/README.md' },
    { path: 'README.md', label: 'README.md' },
  ],
  relatedPages: ['/cordis', '/agent-loop', '/session', '/packages'],
}

export default overview
