import type { PageContent } from '../types'

export const session: PageContent = {
  id: 'session',
  title: 'Session',
  emoji: '💾',
  subtitle: 'append-only 事件日志 —— 单一事实源、恢复、审计',
  hero: [
    'Harness 的 Session 不是“聊天记录数组”，而是一个 append-only 的 SessionEvent 日志。模型看到的 LLM 历史是从日志“派生”出来的投影（deriveMessages），而不是单独存储 —— 这就是它能恢复、能回放、能审计的根本原因。',
    '一次 Agent Loop 的 turn/start、step/start、user/message、assistant/chunk、assistant/message、tool/call、tool/result、step/end、turn/end 全部追加进这个日志。持久化有 JSONL（Zstd）与 SQLite 两个后端，还有投影、压缩、检查点、查询等配套。',
  ],
  learn: [
    'SessionEvent 日志 = 单一事实源',
    'LLM 历史如何从日志派生',
    'JSONL 与 SQLite 两种持久化后端',
    'fork / resume 如何复用历史',
    '投影、压缩、检查点、查询',
  ],
  nodes: [
    {
      id: 'sessions', label: 'ctx.sessions', kind: 'ctx',
      brief: 'SessionStore：创建、追加、读取事件',
      detail: 'packages/core/session 提供 SessionStore。ctx.sessions.create({seed}) 用种子事件创建新会话（fork）；ctx.agents.resume() 恢复既有会话。',
      sources: [{ path: 'packages/core/session/src/index.ts', label: 'core/session/src/index.ts' }],
    },
    {
      id: 'event', label: 'SessionEvent', kind: 'event',
      brief: 'append-only 事件：turn/* step/* tool/* assistant/*',
      detail: '每一个事件有 type（如 turn/start）、id、seq、timestamp 与负载。类型全集见 known-event-types.ts。',
      sources: [{ path: 'packages/core/session/src/types.ts', label: 'session/types.ts' }, { path: 'packages/core/session/src/known-event-types.ts', label: 'known-event-types.ts' }],
    },
    {
      id: 'derive', label: 'deriveMessages', kind: 'file',
      brief: '从事件日志派生 LLM 历史',
      detail: '模型请求的消息序列由日志投影而来：user/message → 用户；assistant/message → 助手；tool/result → 工具结果。空内容 / 已压缩的事件不会污染历史。',
      sources: [{ path: 'packages/core/session/src/surface.ts', label: 'surface.ts' }, { path: 'packages/core/session/src/preparation.ts', label: 'preparation.ts' }],
    },
    {
      id: 'jsonl', label: 'JSONL 持久化', kind: 'backend',
      brief: 'session-persistence-jsonl：每行一个事件',
      detail: '默认后端，追加一行一个 JSON 事件；体积大时用 Zstd 压缩。dsh-base 把 root 指向 $DSH_HOME/sessions。',
      sources: [{ path: 'packages/session/session-persistence-jsonl', label: 'session-persistence-jsonl' }, { path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
    {
      id: 'sqlite', label: 'SQLite 持久化', kind: 'backend',
      brief: 'session-persistence-sqlite：结构化存储',
      detail: '面向搜索 / 统计 / 审计的结构化后端，配合 session-query-sqlite 提供全文检索与精确读取。',
      sources: [{ path: 'packages/session/session-persistence-sqlite', label: 'session-persistence-sqlite' }],
    },
    {
      id: 'persistence', label: 'ctx.persistence', kind: 'ctx',
      brief: '持久化抽象层',
      detail: 'core/session 定义持久化服务接口，具体后端（jsonl/sqlite）作为 Provider 挂载。可恢复、可导出。',
      sources: [{ path: 'packages/core/session/src/index.ts', label: 'core/session/src/index.ts' }],
      docs: [{ path: 'docs/subsystems/persistence.md', label: 'persistence.md' }],
    },
    {
      id: 'checkpoint', label: '检查点', kind: 'concept',
      brief: 'session-checkpoint-policy：请求前打点',
      detail: '在每个模型请求与顶级工具派发前做持久化检查点，崩溃后可回到最近的确定状态。',
      sources: [{ path: 'packages/session/session-checkpoint-policy', label: 'session-checkpoint-policy' }],
    },
    {
      id: 'projection', label: '投影', kind: 'concept',
      brief: 'session-projection：面向 UI 的派生视图',
      detail: '把事件日志投影成 UI 需要的形态（子代理目录、会话列表行、标题……），可缓存（projection-cache）。',
      sources: [{ path: 'packages/session/session-projection', label: 'session-projection' }],
    },
    {
      id: 'compaction', label: '压缩', kind: 'concept',
      brief: 'compaction：超出窗口时压缩历史',
      detail: 'compaction-basic 在 agent/pre-step 触发：判定压力、裁剪工具结果、生成摘要，并把摘要作为新的“源事实”继续追加。',
      sources: [{ path: 'packages/compaction/compaction-basic', label: 'compaction/compaction-basic' }],
      docs: [{ path: 'docs/subsystems/compaction.md', label: 'compaction.md' }],
    },
    {
      id: 'query', label: 'session-query', kind: 'ctx',
      brief: 'ctx.sessionQuery：读取 / 导出 / 搜索',
      detail: 'session-query 提供精确读取、标题、血缘追踪；session-query-sqlite 才启用内容搜索（openAt 可配）。tool-session-query 暴露给模型查询历史。',
      sources: [{ path: 'packages/session-query/session-query', label: 'session-query' }, { path: 'packages/session-query/tool-session-query', label: 'tool-session-query' }],
    },
    {
      id: 'title', label: '会话标题', kind: 'concept',
      brief: '自动生成标题：session-title',
      detail: '默认 first-prompt-llm 策略：用首个 prompt 生成标题；session/title 事件写入日志。',
      sources: [{ path: 'packages/session/session-title', label: 'session-title' }],
    },
  ],
  edges: [
    { id: 'se-sessions-event', from: 'sessions', to: 'event', label: '追加' },
    { id: 'se-event-derive', from: 'event', to: 'derive', label: '派生历史' },
    { id: 'se-sessions-persistence', from: 'sessions', to: 'persistence', label: '抽象' },
    { id: 'se-persistence-jsonl', from: 'persistence', to: 'jsonl', label: '默认' },
    { id: 'se-persistence-sqlite', from: 'persistence', to: 'sqlite', label: '可选' },
    { id: 'se-sessions-checkpoint', from: 'sessions', to: 'checkpoint', label: '打点' },
    { id: 'se-sessions-projection', from: 'sessions', to: 'projection', label: '投影' },
    { id: 'se-event-compaction', from: 'event', to: 'compaction', label: '压缩' },
    { id: 'se-sessions-query', from: 'sessions', to: 'query', label: '查询' },
    { id: 'se-query-sqlite', from: 'query', to: 'sqlite', label: '检索' },
    { id: 'se-sessions-title', from: 'sessions', to: 'title', label: '生成标题' },
  ],
  concepts: [
    {
      title: 'append-only = 单一事实源',
      icon: '📜',
      body: '所有模型消息、工具调用、流式 chunk、审批都追加进日志，不做原地修改。这是“可恢复、可回放、可审计”的根基 —— 一份日志，多种消费方式。',
      sources: [{ path: 'packages/core/session/src/index.ts', label: 'core/session/src/index.ts' }],
    },
    {
      title: '历史是派生的投影',
      icon: '🔁',
      body: 'LLM 请求的历史不是缓存下来的数组，而是每次从日志里按规则派生（deriveMessages）。所以压缩 / 修剪可以安全地只影响“派生结果”而保留完整事实。',
      sources: [{ path: 'packages/core/session/src/surface.ts', label: 'surface.ts' }],
    },
    {
      title: 'fork 与 resume',
      icon: '🍴',
      body: '新会话 = ctx.sessions.create({seed})，用种子事件播种（fork 子代理继承父上下文）；恢复 = ctx.agents.resume() 从日志重建状态。',
      sources: [{ path: 'packages/subagent/subagent-fork-in-process', label: 'subagent-fork-in-process' }],
    },
    {
      title: '两份日志，两种后端',
      icon: '🗄',
      body: 'JSONL（追加友好、可读）与 SQLite（结构查询）。dsh-base 默认 JSONL + 内存 SQLite（openAt: never，仅精确读取），内容搜索需显式开启。',
      sources: [{ path: 'packages/session/session-persistence-jsonl', label: 'persistence-jsonl' }],
    },
  ],
  packages: [
    'packages/core/session',
    'packages/session/session-persistence',
    'packages/session/session-persistence-jsonl',
    'packages/session/session-persistence-sqlite',
    'packages/session/session-projection',
    'packages/session/session-checkpoint-policy',
    'packages/session/session-title',
    'packages/session-query/session-query',
    'packages/session-query/tool-session-query',
    'packages/compaction/compaction-basic',
  ],
  docs: [
    { path: 'docs/subsystems/session.md', label: 'docs/subsystems/session.md' },
    { path: 'docs/subsystems/persistence.md', label: 'docs/subsystems/persistence.md' },
    { path: 'docs/subsystems/compaction.md', label: 'docs/subsystems/compaction.md' },
    { path: 'docs/agent-lifecycle.md', label: 'docs/agent-lifecycle.md' },
  ],
  relatedPages: ['/agent-loop', '/tools', '/subagent'],
}

export default session
