import type { PageContent } from '../types'

export const subagent: PageContent = {
  id: 'subagent',
  title: 'Subagent',
  emoji: '🤖',
  subtitle: '主 Agent 如何创建、控制子 Agent（spawn / fork / 远程后端）',
  hero: [
    'Subagent 是 Harness 的“分工”机制：主 Agent 可以把子任务委托给子 Agent 并行执行，再把结果收回来。它的核心是 Provider 抽象 —— spawn（全新子代理）、fork（继承父上下文）、以及 ACP / Codex / Claude Code / dsh-sdk 等远程后端。',
    '在 dsh-base 中，子代理以插件行方式挂载：subagent-spawn-in-process（providerName: spawn）、subagent-fork-in-process（providerName: fork）；而 tool-subagent / tool-subagent-control / tool-subagent-report 提供模型可见的调用与回报通道。',
  ],
  learn: [
    'ctx.subagents 与 Provider 抽象',
    'spawn（全新）vs fork（继承上下文）',
    '远程后端：ACP / Codex / Claude Code / dsh-sdk',
    'tool-subagent / control / report 调用链',
    '子代理结果如何写回 Session 日志',
  ],
  nodes: [
    {
      id: 'subagents', label: 'ctx.subagents', kind: 'ctx',
      brief: 'SubagentRuntime：按 provider 创建子代理',
      detail: 'packages/subagent/subagent 定义运行时：按名选择 provider 创建子代理、管理生命周期、取回结果。',
      sources: [{ path: 'packages/subagent/subagent/src/index.ts', label: 'subagent/subagent' }],
    },
    {
      id: 'provider-ab', label: 'Provider 抽象', kind: 'concept',
      brief: '同一接口，多种后端共存',
      detail: 'spawn / fork / acp / codex / claude-code / dsh-sdk 都实现同一子代理 Provider 接口，可在一次运行里按名选用。',
      sources: [{ path: 'packages/subagent/subagent', label: 'subagent' }],
      docs: [{ path: 'docs/subsystems/subagent.md', label: 'subagent.md' }],
    },
    {
      id: 'spawn', label: 'spawn', kind: 'provider',
      brief: '全新子代理（默认）',
      detail: 'subagent-spawn-in-process：providerName: spawn。子代理从零开始，带独立上下文；dsh-base 的 tool-subagent 默认 provider: spawn，backgroundMode: continuable（可后台续跑）。',
      sources: [{ path: 'packages/subagent/subagent-spawn-in-process', label: 'spawn-in-process' }, { path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
    {
      id: 'fork', label: 'fork', kind: 'provider',
      brief: '继承父上下文的子代理',
      detail: 'subagent-fork-in-process：providerName: fork。复用父会话历史（Session seed 派生），适合“在父上下文上继续干活”的场景；fork 保持 one-shot。',
      sources: [{ path: 'packages/subagent/subagent-fork-in-process', label: 'fork-in-process' }],
    },
    {
      id: 'acp', label: 'ACP', kind: 'provider',
      brief: 'Agent Client Protocol 远程后端',
      detail: 'subagent-acp：通过 ACP 协议把子任务交给外部 Agent 运行时。',
      sources: [{ path: 'packages/subagent/subagent-acp', label: 'subagent-acp' }],
    },
    {
      id: 'codex', label: 'Codex', kind: 'provider',
      brief: 'OpenAI Codex 后端',
      detail: 'subagent-codex：把子任务委托给 Codex CLI。',
      sources: [{ path: 'packages/subagent/subagent-codex', label: 'subagent-codex' }],
    },
    {
      id: 'claude', label: 'Claude Code', kind: 'provider',
      brief: 'Claude Code 后端',
      detail: 'subagent-claude-code：把子任务委托给 Claude Code CLI。',
      sources: [{ path: 'packages/subagent/subagent-claude-code', label: 'subagent-claude-code' }],
    },
    {
      id: 'dshsdk', label: 'dsh-sdk', kind: 'provider',
      brief: 'Harness 自己的 SDK 后端',
      detail: 'subagent-dsh-sdk：通过官方 SDK 连接另一个 Harness 实例作为子代理。',
      sources: [{ path: 'packages/subagent/subagent-dsh-sdk', label: 'subagent-dsh-sdk' }],
    },
    {
      id: 'tool-sub', label: 'tool-subagent', kind: 'tool',
      brief: '模型可见的 subagent 工具',
      detail: '模型调用 subagent 工具创建子代理（provider: spawn、toolName: subagent、backgroundMode: continuable）；另有 subagent_fork（fork、one-shot）。',
      sources: [{ path: 'packages/subagent/tool-subagent', label: 'tool-subagent' }, { path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
    {
      id: 'control', label: 'tool-subagent-control', kind: 'tool',
      brief: '控制后台子代理：list / send_message',
      detail: 'tool-subagent-control 注册后台子代理的调度工具（list-agents、send_message），让主 Agent 与持续运行的子代理通信。',
      sources: [{ path: 'packages/subagent/tool-subagent-control', label: 'tool-subagent-control' }],
    },
    {
      id: 'report', label: 'tool-subagent-report', kind: 'tool',
      brief: '子代理回报工具',
      detail: '子代理可用 report 工具把结果 / 进度回报给父 Agent；持久记录进 Session 日志，主 Agent 从事件流里消费。',
      sources: [{ path: 'packages/subagent/tool-subagent-report', label: 'tool-subagent-report' }],
    },
    {
      id: 'descriptor', label: 'subagent/descriptor', kind: 'event',
      brief: '子代理描述事件',
      detail: 'session 里以 subagent/descriptor 事件记录子代理身份，投影层据此组织子代理目录，UI 显示子代理执行轨迹。',
      sources: [{ path: 'packages/core/session/src/known-event-types.ts', label: 'known-event-types.ts' }, { path: 'packages/client/ui-subagent', label: 'ui-subagent' }],
    },
  ],
  edges: [
    { id: 'ue-sub-provider', from: 'subagents', to: 'provider-ab', label: '抽象' },
    { id: 'ue-provider-spawn', from: 'provider-ab', to: 'spawn', label: '默认' },
    { id: 'ue-provider-fork', from: 'provider-ab', to: 'fork', label: '继承上下文' },
    { id: 'ue-provider-acp', from: 'provider-ab', to: 'acp', label: '实现' },
    { id: 'ue-provider-codex', from: 'provider-ab', to: 'codex', label: '实现' },
    { id: 'ue-provider-claude', from: 'provider-ab', to: 'claude', label: '实现' },
    { id: 'ue-provider-sdk', from: 'provider-ab', to: 'dshsdk', label: '实现' },
    { id: 'ue-sub-tool', from: 'subagents', to: 'tool-sub', label: '调用' },
    { id: 'ue-tool-control', from: 'tool-sub', to: 'control', label: '后台调度' },
    { id: 'ue-control-report', from: 'control', to: 'report', label: '回报' },
    { id: 'ue-report-descriptor', from: 'report', to: 'descriptor', label: '写日志' },
    { id: 'ue-tool-descriptor', from: 'tool-sub', to: 'descriptor', label: '创建时记录' },
  ],
  concepts: [
    {
      title: 'spawn vs fork',
      icon: '🍴',
      body: 'spawn = 全新子代理，独立上下文，适合并行拆分任务；fork = 继承父上下文（Session seed），适合延续父的思维脉络。默认 tool-subagent 用 spawn。',
      sources: [{ path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
    {
      title: 'Provider 即扩展点',
      icon: '🔌',
      body: '想让 Harness 把子任务派给任何外部 Agent，只需实现一个 Provider：ACP / Codex / Claude Code / dsh-sdk 已证明这一点。这正好是 Longsys AI 集成第三方智能体的入口。',
      sources: [{ path: 'packages/subagent/subagent', label: 'subagent' }],
    },
    {
      title: 'continuable 后台模式',
      icon: '⏳',
      body: 'spawn 子代理默认可后台续跑：主 Agent 创建后继续干活，之后通过 tool-subagent-control（list / send_message）取回或指挥。',
      sources: [{ path: 'packages/subagent/tool-subagent-control', label: 'tool-subagent-control' }],
    },
    {
      title: '结果走事件日志',
      icon: '📜',
      body: '子代理的创建与回报（subagent/descriptor、report）都是 durable 事件，进 Session 日志 —— 因此可审计、可回放、可 UI 展示执行轨迹（ui-subagent）。',
      sources: [{ path: 'packages/core/session/src/known-event-types.ts', label: 'known-event-types.ts' }],
    },
  ],
  packages: [
    'packages/subagent/subagent',
    'packages/subagent/subagent-spawn-in-process',
    'packages/subagent/subagent-fork-in-process',
    'packages/subagent/subagent-in-process-driver',
    'packages/subagent/subagent-acp',
    'packages/subagent/subagent-codex',
    'packages/subagent/subagent-claude-code',
    'packages/subagent/subagent-dsh-sdk',
    'packages/subagent/tool-subagent',
    'packages/subagent/tool-subagent-control',
    'packages/subagent/tool-subagent-report',
  ],
  docs: [
    { path: 'docs/subsystems/subagent.md', label: 'docs/subsystems/subagent.md' },
    { path: 'docs/subsystems/session.md', label: 'docs/subsystems/session.md' },
  ],
  relatedPages: ['/workflow', '/session', '/agent-loop'],
}

export default subagent
