import type { PageContent } from '../types'

export const tools: PageContent = {
  id: 'tools',
  title: 'Tools',
  emoji: '🛠',
  subtitle: 'Tool 注册、schema、执行模式与 pre-execute 权限控制',
  hero: [
    '工具是 Agent 与外部世界交互的“手”。packages/core/tools 定义了一个统一的工具运行时（ToolRuntime）：工具注册、schema 生成、执行模式（并行/排他）、pre-execute 权限裁决、执行与后处理。',
    '一次工具调用经过 tools/pre-execute（approval/权限/guard 裁决）→ 调度（executionMode 分类）→ tools/execute（执行）→ tools/post-execute（后处理）→ tools/result（通知）。每个阶段都是 waterfall，任何插件都能介入。',
  ],
  learn: [
    'ctx.tools 与工具运行时',
    '工具注册与 schema 生成',
    '执行模式：parallel / exclusive',
    'pre-execute 权限控制与 approval',
    '工具族总览：bash / fs / web / subagent / workflow',
  ],
  nodes: [
    {
      id: 'tools-ctx', label: 'ctx.tools', kind: 'ctx',
      brief: 'ToolRuntime：工具注册 + 执行管线',
      detail: 'packages/core/tools 的运行时。维护工具注册表，暴露 schema、executionMode、execute 管线，并触发 tools/* 事件。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'core/tools/src/index.ts' }],
    },
    {
      id: 'tool-def', label: 'defineTool()', kind: 'concept',
      brief: '推荐写法：defineTool() 声明 名称+描述+schema+output+执行函数',
      detail: '官方推荐用 defineTool() 构造工具（tools/schema.ts），再交给 ctx.tools.register() 注册。它声明 name、description、入参 schema（parameters）、规范输出（output.schema + render）与 execute（返回规范 JSON value）。',
      sources: [{ path: 'packages/core/tools/src/schema.ts', label: 'tools/schema.ts' }, { path: 'packages/core/tools/src/types.ts', label: 'types.ts' }],
    },
    {
      id: 'register', label: '注册', kind: 'concept',
      brief: 'ctx.tools.register(...) 挂载工具',
      detail: '各工具插件在启动时向 ctx.tools 注册。dsh-base 挂了一大批：tool-fs、tool-bash、tool-web、tool-subagent、tool-workflow、tool-todo、tool-session-query……',
      sources: [{ path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
    {
      id: 'schema', label: 'JSON Schema', kind: 'file',
      brief: '从 TS 类型派生工具入参 schema',
      detail: 'tools 包把工具参数类型转成 JSON Schema 交给模型（json-schema.ts / ts-types.ts / py-types.ts），保证模型能按规范构造调用。',
      sources: [{ path: 'packages/core/tools/src/json-schema.ts', label: 'json-schema.ts' }],
    },
    {
      id: 'mode', label: 'executionMode', kind: 'concept',
      brief: 'parallel / exclusive 执行分类',
      detail: 'ToolExecutionMode = { kind: parallel } | { kind: exclusive }。isConcurrencySafe 为 true 才 parallel，否则 exclusive 串行。tool-calls.ts 维护有界滚动池。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L344' }, { path: 'packages/core/agent-loop/src/tool-calls.ts', label: 'tool-calls.ts' }],
    },
    {
      id: 'pre', label: 'tools/pre-execute', kind: 'event',
      brief: '预执行裁决：允许 / 拒绝 / 询问',
      detail: 'waterfall 扩展点，返回 PreToolDecision。approval 插件（@deepseek-ai/dsh-user-approval）、权限预设（permission-presets）、guard（安全守卫）都挂在这里。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L152' }],
    },
    {
      id: 'exec', label: 'tools/execute', kind: 'event',
      brief: '真正执行工具',
      detail: 'waterfall 扩展点，返回 ToolExecutionResult。执行载体由各工具提供（如 bash 沙箱执行 shell、fs 读写文件）。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L163' }],
    },
    {
      id: 'post', label: 'tools/post-execute', kind: 'event',
      brief: '后处理：截断 / 摘要 / 物化',
      detail: 'waterfall 扩展点，返回 PostToolDecision。spill（超大结果溢出）、tool-result-pruner（压缩超大结果）在这里处理。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L175' }],
    },
    {
      id: 'guard', label: 'Guard', kind: 'concept',
      brief: '安全守卫：拦截危险工具调用',
      detail: 'guard 包提供规则化守卫，在 pre-execute 阶段拦截不安全的调用（如越权写文件、敏感命令）。',
      sources: [{ path: 'packages/guard/timeout-policy', label: 'guard/timeout-policy' }],
      docs: [{ path: 'docs/subsystems/commands.md', label: 'commands.md' }],
    },
    {
      id: 'approval', label: 'Approval', kind: 'concept',
      brief: '人工审批：approval/asked → approval/decided',
      detail: 'dsh-user-approval 插件按 policy 在 pre-execute 抛出审批：policy=ask 时询问用户，approval/asked 与 approval/decided 都是 durable 事件。',
      sources: [{ path: 'packages/interaction/user-approval', label: 'user-approval' }],
      docs: [{ path: 'docs/subsystems/approval.md', label: 'approval.md' }],
    },
    {
      id: 'result', label: 'tools/result', kind: 'event',
      brief: '结果通知：tool/result 入日志',
      detail: 'tools/result emit 通知监听者；同时 tool/result 作为 durable 事件写入 Session 日志，模型下一轮就能看到结果。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L197' }],
    },
    {
      id: 'tool-family', label: '工具族', kind: 'concept',
      brief: 'bash / fs / web / subagent / workflow / jobs……',
      detail: '工具按能力分族：tool-bash/tool-pwsh（shell）、tool-fs/tool-fs-search（文件）、tool-web/web-search（网络）、tool-subagent（子代理）、tool-workflow（工作流）、tool-jobs（后台任务）、tool-todo、tool-session-query、tool-str-replace-editor 等。',
      sources: [{ path: 'packages/bundle/base/cordis.patch.yml', label: 'base/cordis.patch.yml' }],
    },
  ],
  edges: [
    { id: 'te-ctx-def', from: 'tools-ctx', to: 'tool-def', label: '定义' },
    { id: 'te-ctx-register', from: 'tools-ctx', to: 'register', label: '挂载' },
    { id: 'te-def-schema', from: 'tool-def', to: 'schema', label: '派生' },
    { id: 'te-register-schema', from: 'register', to: 'schema', label: '生成' },
    { id: 'te-ctx-mode', from: 'tools-ctx', to: 'mode', label: '分类' },
    { id: 'te-ctx-pre', from: 'tools-ctx', to: 'pre', label: 'waterfall' },
    { id: 'te-pre-approval', from: 'pre', to: 'approval', label: '审批' },
    { id: 'te-pre-guard', from: 'pre', to: 'guard', label: '守卫' },
    { id: 'te-pre-exec', from: 'pre', to: 'exec', label: '通过后' },
    { id: 'te-exec-post', from: 'exec', to: 'post', label: 'waterfall' },
    { id: 'te-post-result', from: 'post', to: 'result', label: 'emit' },
    { id: 'te-ctx-family', from: 'tools-ctx', to: 'tool-family', label: '注册' },
  ],
  concepts: [
    {
      title: '工具管线的四个阶段',
      icon: '🔧',
      body: 'pre-execute 裁决（能不能执行）→ execute（执行）→ post-execute（结果加工）→ result（通知 + 写日志）。全是 waterfall，任何插件都能插入逻辑。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'core/tools/src/index.ts' }],
    },
    {
      title: '并行与排他',
      icon: '⚖',
      body: '工具自己声明 isConcurrencySafe。safe 的（如只读查询）可并行以提速；不安全或会改状态的（如编辑器）排他串行，防止数据竞争。',
      sources: [{ path: 'packages/core/tools/src/index.ts', label: 'index.ts#L344' }],
    },
    {
      title: '权限在 pre-execute 拦',
      icon: '🛡',
      body: 'approval（人工审批）、permission-presets（read-only/workspace-write/danger-full-access）、guard（规则守卫）都在 tools/pre-execute 汇合，统一裁决。',
      sources: [{ path: 'docs/subsystems/approval.md', label: 'approval.md' }],
    },
    {
      title: '添加一个工具 = 一个插件',
      icon: '➕',
      body: '官方 cookbook 演示：defineTool() → ctx.tools.register() → 打包成插件挂进 profile。这是 Plugin Generator 的「Tool 插件练习」要动手做的事。',
      sources: [{ path: 'docs/cookbook/adding-a-tool.md', label: 'adding-a-tool.md' }],
    },
  ],
  packages: [
    'packages/core/tools',
    'packages/fs/tool-fs',
    'packages/shell/tool-bash',
    'packages/web/tool-web',
    'packages/subagent/tool-subagent',
    'packages/workflow/tool-workflow',
    'packages/interaction/user-approval',
    'packages/guard/timeout-policy',
    'packages/core/agent-loop',
  ],
  docs: [
    { path: 'docs/subsystems/tools.md', label: 'docs/subsystems/tools.md' },
    { path: 'docs/cookbook/adding-a-tool.md', label: 'docs/cookbook/adding-a-tool.md' },
    { path: 'docs/tool-catalog.md', label: 'docs/tool-catalog.md' },
    { path: 'docs/subsystems/approval.md', label: 'docs/subsystems/approval.md' },
  ],
  relatedPages: ['/agent-loop', '/permission', '/plugin-generator'],
}

export default tools
