import type { PageContent } from '../types'

export const webui: PageContent = {
  id: 'webui',
  title: 'Web UI / Slots',
  emoji: '🎨',
  subtitle: 'React Client 与 UI 插件 —— 39 个 client 子包组成的 Slots 系统',
  hero: [
    'Harness 的 Web UI 本身就是“一切皆插件”的体现：apps/web 的 React 入口 + packages/client/* 的 39 个 UI 插件。每个 UI 插件通过 ctx.slots.register(key, Component, children?) 把自己的组件挂到 Slots（插槽）树上。',
    'Slots 是一个 DAG：父 slot 声明子 slot，插件向任意 slot 注册组件，最终由 root slot 挂载成完整界面。ui-sidebar、ui-conversation、ui-tool、ui-skill、ui-subagent、ui-permission、ui-trajectory、ui-workflow-run…… 页面插件都在这套系统里。',
  ],
  learn: [
    'client 包的运行架构（shell / runtime / modules）',
    'ctx.slots 与插槽 DAG',
    'UI 插件如何注册与挂载',
    '几个代表性 UI 插件：conversation / tool / trajectory',
    '与后端的连接：connection / hmr',
  ],
  nodes: [
    {
      id: 'web-app', label: 'apps/web', kind: 'bundle',
      brief: 'React 应用入口',
      detail: 'apps/web 是浏览器端入口，加载 web-react 客户端运行时并挂载 root slot。',
      sources: [{ path: 'apps/web/src/main.ts', label: 'apps/web/src/main.ts' }],
    },
    {
      id: 'client', label: 'client 包族', kind: 'package',
      brief: '39 个 client 子包',
      detail: 'packages/client/* 拆成 shell、runtime、modules、UI 插件等 39 个子包。目录即架构：web / web-react / runtime / modules / connection / hmr / ui-*……',
      sources: [{ path: 'packages/client/AGENTS.md', label: 'client/AGENTS.md' }],
    },
    {
      id: 'web-react', label: 'client/web-react', kind: 'package',
      brief: 'React 客户端运行时',
      detail: '提供 React 侧的 Cordis ctx 桥接：把后端的 ctx.slots、ctx.events 映射到浏览器端，UI 插件在浏览器里以 React 组件运行。',
      sources: [{ path: 'packages/client/web-react', label: 'client/web-react' }],
    },
    {
      id: 'slots', label: 'ctx.slots', kind: 'ctx',
      brief: '插槽系统：register(key, Component, children?)',
      detail: 'UI 插件向 slot 注册组件。slot 构成 DAG：父 slot 指定子 slot，root slot 挂载整棵树。ui-slots 包提供 slot 基础设施。',
      sources: [{ path: 'packages/client/ui-slots', label: 'client/ui-slots' }],
    },
    {
      id: 'root-slot', label: 'root slot', kind: 'concept',
      brief: '整棵 UI 树的根',
      detail: '应用启动时把 root slot 挂到 #app；所有 UI 插件注册的组件最终在这棵树上就位。',
      sources: [{ path: 'packages/client/ui-layout', label: 'ui-layout' }],
    },
    {
      id: 'ui-sidebar', label: 'ui-sidebar', kind: 'package',
      brief: '侧边栏（会话列表 / 工作区）',
      detail: '提供侧边导航，列出会话、标题、工作区。',
      sources: [{ path: 'packages/client/ui-sidebar', label: 'ui-sidebar' }],
    },
    {
      id: 'ui-conv', label: 'ui-conversation', kind: 'package',
      brief: '对话流',
      detail: '渲染会话里的消息流：用户消息、assistant/chunk 打字机、工具调用卡片。消费 session/event。',
      sources: [{ path: 'packages/client/ui-conversation', label: 'ui-conversation' }],
    },
    {
      id: 'ui-tool', label: 'ui-tool', kind: 'package',
      brief: '工具调用 UI',
      detail: '展示工具调用参数、状态、结果，以及审批交互。',
      sources: [{ path: 'packages/client/ui-tool', label: 'ui-tool' }],
    },
    {
      id: 'ui-skill', label: 'ui-skill', kind: 'package',
      brief: '技能面板',
      detail: '展示 ctx.skills 目录，支持查看 / 开关技能。',
      sources: [{ path: 'packages/client/ui-skill', label: 'ui-skill' }],
    },
    {
      id: 'ui-sub', label: 'ui-subagent', kind: 'package',
      brief: '子代理轨迹',
      detail: '展示子代理执行树、状态、结果。',
      sources: [{ path: 'packages/client/ui-subagent', label: 'ui-subagent' }],
    },
    {
      id: 'ui-trajectory', label: 'ui-trajectory', kind: 'package',
      brief: '轨迹回放',
      detail: '把 turn/step/tool 事件流可视化为可回放的轨迹。',
      sources: [{ path: 'packages/client/ui-trajectory', label: 'ui-trajectory' }],
    },
    {
      id: 'ui-wfrun', label: 'ui-workflow-run', kind: 'package',
      brief: '工作流运行视图',
      detail: '展示 workflow run 的步骤与结果。',
      sources: [{ path: 'packages/client/ui-workflow-run', label: 'ui-workflow-run' }],
    },
    {
      id: 'connection', label: 'client/connection', kind: 'backend',
      brief: '浏览器与后端连接',
      detail: '浏览器端通过 connection 与后端同步会话与事件流。',
      sources: [{ path: 'packages/client/connection', label: 'client/connection' }],
    },
    {
      id: 'hmr', label: 'client/hmr', kind: 'backend',
      brief: 'UI 热更新',
      detail: '插件级 HMR：改一个 UI 插件不用刷新整页。',
      sources: [{ path: 'packages/client/hmr', label: 'client/hmr' }],
    },
  ],
  edges: [
    { id: 'ue-web-react', from: 'web-app', to: 'web-react', label: '加载' },
    { id: 'ue-web-root', from: 'web-app', to: 'root-slot', label: '挂载' },
    { id: 'ue-react-slots', from: 'web-react', to: 'slots', label: '桥接' },
    { id: 'ue-react-connection', from: 'web-react', to: 'connection', label: '连接' },
    { id: 'ue-react-hmr', from: 'web-react', to: 'hmr', label: '热更' },
    { id: 'ue-slots-root', from: 'slots', to: 'root-slot', label: '根' },
    { id: 'ue-slots-sidebar', from: 'slots', to: 'ui-sidebar', label: '注册' },
    { id: 'ue-slots-conv', from: 'slots', to: 'ui-conv', label: '注册' },
    { id: 'ue-slots-tool', from: 'slots', to: 'ui-tool', label: '注册' },
    { id: 'ue-slots-skill', from: 'slots', to: 'ui-skill', label: '注册' },
    { id: 'ue-slots-sub', from: 'slots', to: 'ui-sub', label: '注册' },
    { id: 'ue-slots-trajectory', from: 'slots', to: 'ui-trajectory', label: '注册' },
    { id: 'ue-slots-wfrun', from: 'slots', to: 'ui-wfrun', label: '注册' },
  ],
  concepts: [
    {
      title: 'Slots 是 UI 的“能力缝”',
      icon: '🔌',
      body: '和后端服务一样，UI 也走插件化：ctx.slots.register(key, Component, children?) 向插槽注册。想加一个侧栏面板 = 写一个 UI 插件注册进 sidebar slot。',
      sources: [{ path: 'packages/client/ui-slots', label: 'ui-slots' }],
    },
    {
      title: 'UI 插件与后端事件对偶',
      icon: '🔁',
      body: 'ui-conversation 渲染 assistant/chunk；ui-tool 渲染 tool/call 与审批；ui-trajectory 回放 turn/step/tool —— 每个 UI 插件都在消费 Session 事件流的某个投影。',
      sources: [{ path: 'packages/client/ui-conversation', label: 'ui-conversation' }],
    },
    {
      title: '39 个包 = 可裁剪的 UI',
      icon: '🧩',
      body: '想做一个“只对话不要工作流”的界面？只挂 ui-conversation，不挂 ui-workflow-run 即可。这正是按需裁剪前端的方式。',
      sources: [{ path: 'packages/client/AGENTS.md', label: 'client/AGENTS.md' }],
    },
    {
      title: '理解这一层 = 掌握魔改 Harness 的关键',
      icon: '🔑',
      body: '把 Learning Lab 做成 dsh-learning-lab-plugin 的本质：写一个注册进某 slot 的 UI 插件。看懂 slots 系统就掌握了“怎么把 Harness 魔改成自己的 Agent”的核心技术。',
      sources: [{ path: 'packages/client/ui-slots', label: 'ui-slots' }],
    },
  ],
  packages: [
    'apps/web',
    'packages/client/web',
    'packages/client/web-react',
    'packages/client/runtime',
    'packages/client/modules',
    'packages/client/connection',
    'packages/client/hmr',
    'packages/client/ui-slots',
    'packages/client/ui-layout',
    'packages/client/ui-sidebar',
    'packages/client/ui-conversation',
    'packages/client/ui-tool',
    'packages/client/ui-skill',
    'packages/client/ui-subagent',
    'packages/client/ui-trajectory',
    'packages/client/ui-workflow-run',
  ],
  docs: [
    { path: 'packages/client/AGENTS.md', label: 'packages/client/AGENTS.md' },
    { path: 'docs/subsystems/web.md', label: 'docs/subsystems/web.md' },
    { path: 'docs/web-styling.md', label: 'docs/web-styling.md' },
  ],
  relatedPages: ['/cordis', '/plugin-generator', '/session'],
}

export default webui
